version: '3.8'

services:
 postgres:
  image: postgres:13
  restart: always
  environment:
    POSTGRES_PASSWORD: ${DB_PASS}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}
  volumes:
   - ${POSTGRES_BACKUP_PATH}:${POSTGRES_CONTAINER_PATH}
  ports:
   - 5432:5432
 django:
  image: service
  restart: always
  environment:
   DJANGO_DB_HOST: ${DB_HOST}
   DJANGO_DB_NAME: ${DB_NAME}
   DJANGO_DB_USER: ${DB_USER}
   DJANGO_DB_PASS: ${DB_PASS}
   DJANGO_DB_PORT: "5432"
   DJANGO_DEBUG: "False"
  volumes:
    - ${DJANGO_MEDIA_UPLOADS_BACKUP_PATH}:${DJANGO_MEDIA_UPLOADS_CONTAINER_PATH}
  build:
   context: .
   dockerfile: docker-file-service.conf
  depends_on:
   - postgres
# Для того, чтобы запустить приложение без wsgi, необходимо закомментировать 33 строку и раскомментировать 34
  command: bash -c "python3 /app/manage.py migrate && uwsgi --ini /app/uwsgi.ini"
#  command: bash -c "python3 /app/manage.py migrate && python3 /app/manage.py runserver ${WEB_HOST_ADDRESS}"
  ports:
   - "8000:8000"